var config = {};

config.api_version = 'v2.8';

config.adAccount = {
  fields: 'account_status,age,amount_spent,balance,business_street,business_city,account_id,currency,name,user_role,agency_client_declaration,business_country_code,business_name,business_state,business_street2,business_zip,created_time,end_advertiser,funding_source,id,media_agency,owner,partner,timezone_name'
}

config.pageMetrics = {
  pageFields: 'about,access_token,written_by,awards,app_id,app_links,artists_we_like,affiliation,attire,band_interests,band_members,best_page,bio,birthday,booking_agent,built,can_checkin,can_post,category,category_list,checkins,contact_address,country_page_likes,cover,culinary_team,current_location,description,directed_by,display_subtext,displayed_message_response_time,emails,engagement,fan_count,featured_video,features,food_styles,founded,general_info,general_manager,genre,global_brand_page_name,global_brand_root_id,has_added_app,hometown,hours,id,impressum,influences,is_always_open,is_community_page,is_permanently_closed,is_published,is_unclaimed,is_verified,link,location,members,mission,mpg,name,name_with_location_descriptor,network,new_like_count,phone,offer_eligible,company_overview,overall_star_rating,parent_page,payment_options,personal_info,personal_interests,place_type,price_range,produced_by,products,promotion_eligible,public_transit,rating_count,record_label,release_date,restaurant_services,restaurant_specialties,schedule,screenplay_by,season,single_line_address,starring,start_info,store_location_descriptor,store_number,studio,talking_about_count,unread_message_count,unread_notif_count,unseen_message_count,username,verification_status,website,were_here_count',
  pageRatings: 'rating,created_time,has_rating,has_review,review_text,open_graph_story,reviewer',
  pagePhotos: 'album,backdated_time,backdated_time_granularity,can_backdate,created_time,can_tag,event,from,icon,images,name,link,name_tags,updated_time,webp_images,target,place,width,height,can_delete,id,page_story_id,picture',
  pagePosts: 'caption,created_time,description,from,full_picture,icon,id,instagram_eligibility,is_expired,is_hidden,is_instagram_eligible,is_popular,is_published,is_spherical,link,message,message_tags,name,permalink_url,picture,place,privacy,promotion_status,scheduled_publish_time,shares,source,status_type,story,story_tags,subscribed,target,targeting,timeline_visibility,type,updated_time',
  pageInsights: [{
    method: 'get',
    relative_url: '/insights/page_stories/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_storytellers/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_paid/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_paid_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_organic/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_organic_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_by_city_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_by_country_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_impressions_by_locale_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_engaged_users/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_consumptions/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_consumptions_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_consumptions_by_consumption_type/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_consumptions_by_consumption_type_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_places_checkin_total/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_places_checkin_total_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_places_checkin_mobile/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_places_checkin_mobile_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_places_checkins_by_age_gender/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_places_checkins_by_locale/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_places_checkins_by_country/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_negative_feedback/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_negative_feedback_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_negative_feedback_by_type/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_negative_feedback_by_type_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_positive_feedback_by_type/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_positive_feedback_by_type_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_online/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_online_per_day/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_fan_adds_by_paid_non_paid_unique/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_actions_post_reactions_like_total/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_actions_post_reactions_wow_total/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_actions_post_reactions_haha_total/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_actions_post_reactions_sorry_total/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_actions_post_reactions_anger_total/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_actions_post_reactions_total/day'
  }, {
    method: 'get',
    relative_url: '/insights/page_cta_clicks_logged_in_total/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_cta_clicks_logged_in_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_cta_clicks_by_site_logged_in_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_cta_clicks_by_age_gender_logged_in_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_locale'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_city'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_country'
  }, {
    method: 'get',
    relative_url: '/insights/page_fan_adds'
  }, {
    method: 'get',
    relative_url: '/insights/page_fan_adds_unique'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_by_like_source'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_by_like_source_unique'
  }, {
    method: 'get',
    relative_url: '/insights/page_fan_removes'
  }, {
    method: 'get',
    relative_url: '/insights/page_fan_removes_unique'
  }, {
    method: 'get',
    relative_url: '/insights/page_fans_by_unlike_source_unique'
  }, {
    method: 'get',
    relative_url: '/insights/page_views_total/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_views_logout'
  }, {
    method: 'get',
    relative_url: '/insights/page_views_logged_in_total/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_views_logged_in_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_views/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_views_paid/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_views_organic/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_views_autoplayed/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_views_click_to_play/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_views_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_repeat_views/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_complete_views_30s/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_complete_views_30s_paid/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_complete_views_30s_organic/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_complete_views_30s_autoplayed/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_complete_views_30s_click_to_play/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_complete_views_30s_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_video_complete_views_30s_repeat_views/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_posts_impressions/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_posts_impressions_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_posts_impressions_paid/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_posts_impressions_paid_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_posts_impressions_organic/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/page_posts_impressions_organic_unique/days_28'
  }, {
    method: 'get',
    relative_url: '/insights/post_interests_impressions'
  }, {
    method: 'get',
    relative_url: '/insights/post_interests_impressions_unique'
  }],
  pagePostsInsights: [{
    method: 'get',
    relative_url: '/insights/post_stories'
  }, {
    method: 'get',
    relative_url: '/insights/post_storytellers'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_paid'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_paid_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_fan'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_fan_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_fan_paid'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_fan_paid_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_organic'
  }, {
    method: 'get',
    relative_url: '/insights/post_impressions_organic_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_consumptions'
  }, {
    method: 'get',
    relative_url: '/insights/post_consumptions_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_engaged_users'
  }, {
    method: 'get',
    relative_url: '/insights/post_negative_feedback'
  }, {
    method: 'get',
    relative_url: '/insights/post_negative_feedback_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_engaged_fan'
  }, {
    method: 'get',
    relative_url: '/insights/post_fan_reach'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_avg_time_watched'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_complete_views_organic'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_complete_views_organic_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_complete_views_paid'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_complete_views_paid_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_organic'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_organic_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_paid'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_paid_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_length'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_autoplayed'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_clicked_to_play'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_10s_unique'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_10s_autoplayed'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_10s_clicked_to_play'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_10s_organic'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_10s_paid'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_10s_sound_on'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_sound_on'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_view_time_organic'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_view_time'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_view_time_by_region_id'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_views_by_distribution_type'
  }, {
    method: 'get',
    relative_url: '/insights/post_video_view_time_by_distribution_type'
  }]
}

config.insightMetrics = {
  campaignFields: 'adlabels,brand_lift_studies,budget_rebalance_flag,buying_type,can_create_brand_lift_study,configured_status,can_use_spend_cap,created_time,effective_status,id,name,account_id,objective,recommendations,spend_cap,start_time,status,stop_time,updated_time',
  adsetFields: 'adlabels,adset_schedule,attribution_window_days,bid_amount,bid_info,billing_event,budget_remaining,campaign_id,configured_status,created_time,creative_sequence,account_id,daily_budget,effective_status,end_time,frequency_cap,frequency_cap_reset_period,frequency_control_specs,id,is_autobid,is_average_price_pacing,lifetime_budget,lifetime_frequency_cap,lifetime_imps,name,optimization_goal,pacing_type,promoted_object,recommendations,recurring_budget_semantics,rf_prediction_id,rtb_flag,start_time,status,targeting,time_based_ad_rotation_id_blocks,time_based_ad_rotation_intervals,updated_time,use_new_app_click',
  adFields: 'account_id,ad_review_feedback,adlabels,adset_id,bid_amount,bid_info,bid_type,campaign_id,configured_status,conversion_specs,created_time,creative,effective_status,id,last_updated_by_app_id,name,recommendations,status,tracking_specs,updated_time',
  adFieldsAdCreatives: 'adlabels,body,effective_instagram_story_id,effective_object_story_id,image_crops,image_url,instagram_actor_id,instagram_permalink_url,instagram_story_id,link_og_id,link_url,name,object_id,object_story_id,object_story_spec,object_type,object_url,thumbnail_url,title,url_tags',
  insightsCampaignFields: 'website_ctr,actions,buying_type,call_to_action_clicks,app_store_clicks,campaign_name,canvas_avg_view_percent,cost_per_10_sec_video_view,clicks,canvas_avg_view_time,campaign_id,cost_per_inline_link_click,cost_per_estimated_ad_recallers,cost_per_inline_post_engagement,cost_per_action_type,cost_per_total_action,cost_per_unique_click,cost_per_unique_action_type,cost_per_unique_inline_link_click,adset_name,cpc,cpm,cpp,ctr,date_start,date_stop,deeplink_clicks,estimated_ad_recall_rate,estimated_ad_recallers,frequency,impressions,inline_link_click_ctr,inline_link_clicks,inline_post_engagement,newsfeed_avg_position,action_values,newsfeed_clicks,newsfeed_impressions,objective,place_page_name,account_name,reach,relevance_score,social_clicks,account_id,social_impressions,social_reach,social_spend,spend,total_action_value,total_actions,total_unique_actions,unique_actions,unique_clicks,unique_ctr,unique_impressions,unique_inline_link_click_ctr,unique_inline_link_clicks,unique_link_clicks_ctr,unique_social_clicks,unique_social_impressions,video_10_sec_watched_actions,video_15_sec_watched_actions,video_30_sec_watched_actions,video_avg_pct_watched_actions,video_avg_percent_watched_actions,video_avg_sec_watched_actions,video_avg_time_watched_actions,video_complete_watched_actions,video_p100_watched_actions,video_p25_watched_actions,video_p50_watched_actions,video_p75_watched_actions,video_p95_watched_actions,website_clicks',
  insightsAdFields: 'website_ctr,adset_id,ad_name,actions,ad_id,buying_type,call_to_action_clicks,app_store_clicks,campaign_name,canvas_avg_view_percent,cost_per_10_sec_video_view,clicks,canvas_avg_view_time,campaign_id,cost_per_inline_link_click,cost_per_estimated_ad_recallers,cost_per_inline_post_engagement,cost_per_action_type,cost_per_total_action,cost_per_unique_click,cost_per_unique_action_type,cost_per_unique_inline_link_click,adset_name,cpc,cpm,cpp,ctr,date_start,date_stop,deeplink_clicks,estimated_ad_recall_rate,estimated_ad_recallers,frequency,impressions,inline_link_click_ctr,inline_link_clicks,inline_post_engagement,newsfeed_avg_position,action_values,newsfeed_clicks,newsfeed_impressions,objective,place_page_name,account_name,reach,relevance_score,social_clicks,account_id,social_impressions,social_reach,social_spend,spend,total_action_value,total_actions,total_unique_actions,unique_actions,unique_clicks,unique_ctr,unique_impressions,unique_inline_link_click_ctr,unique_inline_link_clicks,unique_link_clicks_ctr,unique_social_clicks,unique_social_impressions,video_10_sec_watched_actions,video_15_sec_watched_actions,video_30_sec_watched_actions,video_avg_pct_watched_actions,video_avg_percent_watched_actions,video_avg_sec_watched_actions,video_avg_time_watched_actions,video_complete_watched_actions,video_p100_watched_actions,video_p25_watched_actions,video_p50_watched_actions,video_p75_watched_actions,video_p95_watched_actions,website_clicks',
  insightsAdsetFields: 'adset_id,adset_name,app_store_clicks,call_to_action_clicks,campaign_id,campaign_name,canvas_avg_view_percent,canvas_avg_view_time,clicks,actions,cost_per_10_sec_video_view,cost_per_estimated_ad_recallers,account_name,cost_per_total_action,cost_per_unique_action_type,cost_per_unique_click,cost_per_unique_inline_link_click,cost_per_inline_post_engagement,cpc,cpm,cpp,date_start,date_stop,deeplink_clicks,estimated_ad_recall_rate,estimated_ad_recallers,frequency,impressions,inline_link_click_ctr,inline_link_clicks,inline_post_engagement,objective,reach,social_clicks,social_impressions,social_reach,social_spend,spend,total_action_value,total_actions,total_unique_actions,unique_actions,unique_clicks,unique_ctr,unique_impressions,unique_inline_link_click_ctr,unique_inline_link_clicks,unique_link_clicks_ctr,unique_social_clicks,ctr,unique_social_impressions,video_15_sec_watched_actions,video_30_sec_watched_actions,video_avg_pct_watched_actions,video_avg_percent_watched_actions,video_avg_sec_watched_actions,video_complete_watched_actions,video_p100_watched_actions,video_p25_watched_actions,video_p50_watched_actions,video_p75_watched_actions,video_avg_time_watched_actions,video_p95_watched_actions,website_clicks,website_ctr,account_id,video_10_sec_watched_actions,cost_per_action_type,cost_per_inline_link_click'
}

module.exports = config;
