var mongoose = require('mongoose');

var campaignInsightMetricsSchema = mongoose.Schema({
  website_ctr: [],
  actions: [],
  call_to_action_clicks: Number,
  app_store_clicks: Number,
  name: String,
  canvas_avg_view_percent: Number,
  clicks: Number,
  canvas_avg_view_time: Number,
  id: String,
  configured_status: String,
  effective_status: String,
  cost_per_inline_link_click: Number,
  cost_per_estimated_ad_recallers: Number,
  cost_per_inline_post_engagement: Number,
  cost_per_action_type: [],
  cost_per_total_action: Number,
  cost_per_unique_click: Number,
  cost_per_unique_action_type: [],
  cost_per_unique_inline_link_click: Number,
  cost_per_10_sec_video_view: [],
  cpc: Number,
  cpm: Number,
  cpp: Number,
  ctr: Number,
  created_time: Date,
  updated_time: Date,
  start_time: Date,
  stop_time: Date,
  date_start: Date,
  date_stop: Date,
  deeplink_clicks: Number,
  estimated_ad_recall_rate: Number,
  estimated_ad_recallers: Number,
  frequency: Number,
  impressions: Number,
  inline_link_click_ctr: Number,
  inline_link_clicks: Number,
  inline_post_engagement: Number,
  newsfeed_avg_position: Number,
  newsfeed_clicks: Number,
  newsfeed_impressions: Number,
  objective: String,
  account_name: String,
  reach: Number,
  relevance_score: {},
  social_clicks: Number,
  account_id: String,
  social_impressions: Number,
  social_reach: Number,
  social_spend: Number,
  spend: Number,
  total_action_value: Number,
  total_actions: Number,
  total_unique_actions: Number,
  unique_actions: [],
  unique_clicks: Number,
  unique_ctr: Number,
  unique_impressions: Number,
  unique_inline_link_click_ctr: Number,
  unique_inline_link_clicks: Number,
  unique_link_clicks_ctr: Number,
  unique_social_clicks: Number,
  unique_social_impressions: Number,
  video_10_sec_watched_actions: [],
  video_15_sec_watched_actions: [],
  video_30_sec_watched_actions: [],
  video_avg_pct_watched_actions: [],
  video_avg_percent_watched_actions: [],
  video_avg_sec_watched_actions: [],
  video_complete_watched_actions: [],
  video_p25_watched_actions: [],
  video_p50_watched_actions: [],
  video_p75_watched_actions: [],
  video_p95_watched_actions: [],
  video_p100_watched_actions: [],
  video_avg_time_watched_actions: [],
  website_clicks: Number,
  scan_id: String,
  currency: {}
});

campaignInsightMetricsModel = mongoose.model('Campaign_Insight_Metrics', campaignInsightMetricsSchema);

module.exports = campaignInsightMetricsModel
