var mongoose = require('mongoose');

var postMetricsSchema = mongoose.Schema({
  caption: String,
  from: {},
  full_picture: String,
  icon: String,
  id: String,
  instagram_eligibility: String,
  is_expired: Boolean,
  is_hidden: Boolean,
  is_instagram_eligible: Boolean,
  is_popular: Boolean,
  is_published: Boolean,
  is_spherical: Boolean,
  link: String,
  status_type: String,
  message: String,
  name: String,
  description: String,
  created_time: Date,
  updated_time: Date,
  type: String,
  status_type: String,
  story: String,
  story_tags: [],
  timeline_visibility: String,
  type: String,
  picture: String,
  permalink_url: String,
  privacy: {},
  promotion_status: String,
  post_stories: Number,
  post_storytellers: Number,
  post_impressions: Number,
  post_impressions_unique: Number,
  post_impressions_paid: Number,
  post_impressions_paid_unique: Number,
  post_impressions_fan: Number,
  post_impressions_fan_unique: Number,
  post_impressions_fan_paid: Number,
  post_impressions_fan_paid_unique: Number,
  post_impressions_organic: Number,
  post_impressions_organic_unique: Number,
  post_consumptions: Number,
  post_consumptions_unique: Number,
  post_engaged_users: Number,
  post_negative_feedback: Number,
  post_negative_feedback_unique: Number,
  post_engaged_fan: Number,
  post_fan_reach: Number,
  post_video_avg_time_watched: Number,
  post_video_complete_views_organic: Number,
  post_video_complete_views_organic_unique: Number,
  post_video_complete_views_paid: Number,
  post_video_complete_views_paid_unique: Number,
  post_video_views_organic: Number,
  post_video_views_organic_unique: Number,
  post_video_views_paid: Number,
  post_video_views_paid_unique: Number,
  post_video_length: Number,
  post_video_views: Number,
  post_video_views_unique: Number,
  post_video_views_autoplayed: Number,
  post_video_views_clicked_to_play: Number,
  post_video_views_10s_unique: Number,
  post_video_views_10s_autoplayed: Number,
  post_video_views_10s_clicked_to_play: Number,
  post_video_views_10s_organic: Number,
  post_video_views_10s_paid: Number,
  post_video_views_10s_sound_on: Number,
  post_video_views_sound_on: Number,
  post_video_view_time_organic: Number,
  post_video_view_time: Number,
  post_video_view_time_by_age_bucket_and_gender: {},
  post_video_view_time_by_region_id: {},
  post_video_views_by_distribution_type: {},
  post_video_view_time_by_distribution_type: {},
  page_id: String,
  scan_id: String,
  currency: {}
});

postMetricsModel = mongoose.model('Post_Metrics', postMetricsSchema);

module.exports = postMetricsModel
